// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using IO.Swagger.Model;

namespace ReisekostenNative.iOS
{
	public partial class BelegeTableViewCell : UITableViewCell
	{
		public BelegeTableViewCell (IntPtr handle) : base (handle)
		{
		}

        public void setCellData(Beleg newData) {
            betrag.Text = newData.Betrag.ToString();
            bezeichnung.Text = newData.Description;
            datum.Text = "test";
            //image.Image = UIImage.fr;
            //status.Image = new UIImage();
        }
	}
}
