// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

using Foundation;
using UIKit;
using IO.Swagger.Model;
using ReisekostenNative.Services;

namespace ReisekostenNative.iOS
{
	public partial class BelegeTableViewController : UITableViewController
	{
		public BelegeTableViewController (IntPtr handle) : base (handle)
		{
		}

        List<Beleg> belege = new List<Beleg>();
        string user = "";

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            initTableView();
        }

        public void initTableView()
        {
            TableView.RowHeight = UITableView.AutomaticDimension;
            TableView.EstimatedRowHeight = 92;
            TableView.AlwaysBounceVertical = false;
            TableView.RefreshControl = new UIRefreshControl();
            TableView.RefreshControl.ValueChanged += refreshTable;
            UIService.Instance.GetBelege(user,(o) => setBelege(o));
        }

        private void refreshTable(object sender, EventArgs e)
        {
            UIService.Instance.GetBelege(user, (o) => setBelege(o));
        }

        private void setBelege(Task<List<Beleg>> o)
        {
            belege = o.Result;
            InvokeOnMainThread(() => {
                TableView.ReloadData();
                TableView.RefreshControl.EndRefreshing();
            });
        }

        public void setUser(string newUser) {
            user = newUser;
        }

        public string getUser() {
            return user;
        }

        public override nint NumberOfSections(UITableView tableView)
        {
            return 1;
        }

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return belege.Capacity;
        }

        public override nfloat GetHeightForRow(UITableView tableView, NSIndexPath indexPath)
        {
            return 92;
        }

        public override nfloat EstimatedHeight(UITableView tableView, NSIndexPath indexPath)
        {
            return 92;
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("belege", indexPath);
            if(cell is BelegeTableViewCell && belege != null && belege.Capacity > indexPath.Row) {
                var belegCell = cell as BelegeTableViewCell;
                belegCell.setCellData(belege[indexPath.Row]);
            }
            return cell;
        }

        public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
        {
            tableView.DeselectRow(indexPath, true);
            // Details öffnen
            var viewController = Storyboard.InstantiateViewController("BelegNeu") as BelegNeuTableViewController;
            viewController.setSavedBeleg(belege[indexPath.Row]);
            viewController.setUser(user);
            NavigationController.ShowViewController(viewController, null);
        }
	}
}
