// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

using Foundation;
using UIKit;
using ReisekostenNative.Services;

namespace ReisekostenNative.iOS
{
    public partial class BelegNeuTableViewController : UITableViewController
	{
        bool datumExp = false;
        bool artExp = false;

        public BelegNeuTableViewController (IntPtr handle) : base (handle)
		{
            
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            datum.MaximumDate = new NSDate();
            art.Model = new ArtenPickerViewModel();
            UIService.Instance.GetBelegarten((o) => setArten(o));
        }

        private void setArten(Task<List<string>> o) {
            ((ArtenPickerViewModel)art.Model).setArten(o.Result, artValue);
            art.ReloadComponent(0);
        }

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            nint ret = 0;
            if (section == 0)
            {
                ret++;
                if (datumExp)
                {
                    ret++;
                }
            }
            else if (section == 1)
            {
                ret++;
                if (artExp)
                {
                    ret++;
                }
            }
            else if (section == 5)
            {
                ret++;
                if (beschreibung != null && beschreibung.Text != null && beschreibung.Text.Length > 0)
                {
                    ret++;
                }
            }
            else if (section == 6)
            {
                ret++;
                if (beleg != null && beleg.Image != null)
                {
                    ret++;
                }
            }
            else
            {
                ret++;
            }
            return ret;
        }

        public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
        {
            if (indexPath.Row == 0)
            {
                if (indexPath.Section == 0)
                {
                    datumExp = !datumExp;
                }
                else if (indexPath.Section == 1)
                {
                    artExp = !artExp;
                }
            }
            tableView.ReloadData();
        }

        public override NSIndexPath WillSelectRow(UITableView tableView, NSIndexPath indexPath)
        {
            if ((indexPath.Section == 0 || indexPath.Section == 1 || indexPath.Section == 5 || indexPath.Section == 6) && indexPath.Row == 0)
            {
                return indexPath;
            }
            return null;
        }

        public class ArtenPickerViewModel : UIPickerViewModel
        {

            List<string> arten = new List<string>();
            UILabel artVal = new UILabel();

            public void setArten(List<string> newArten, UILabel newArtVal) {
                arten = newArten;
                artVal = newArtVal;
            }

            public override nint GetRowsInComponent(UIPickerView pickerView, nint component)
            {
                return arten.Capacity;
            }

            public override string GetTitle(UIPickerView pickerView, nint row, nint component)
            {
                return arten[(int)row];
            }

            public override nint GetComponentCount(UIPickerView pickerView)
            {
                return 1;
            }

            public override void Selected(UIPickerView pickerView, nint row, nint component)
            {
                artVal.Text = arten[(int)row];
            }

        }
	}
}
