// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ReisekostenNative.iOS
{
    public partial class BelegSpeichernSegue : UIStoryboardSegue
	{
        public BelegSpeichernSegue (IntPtr handle) : base (handle)
		{
		}

        public override void Perform()
        {

            var src = SourceViewController as BelegNeuTableViewController;
            if (src != null) {
                var tabView = src.TableView as BelegNeuTableView;
                if (tabView != null && tabView.isDataValid()) {
                    
                    src.NavigationController.PopViewController(true);
                }
                else
                {
                    //Create Alert
                    var okAlertController = UIAlertController.Create("Fehler", "Fehler beim Speichern des Belegs", UIAlertControllerStyle.Alert);

                    //Add Action
                    okAlertController.AddAction(UIAlertAction.Create("Ok", UIAlertActionStyle.Default, null));

                    // Present Alert
                    src.PresentViewController(okAlertController, true, null);
                }
            }
        }
	}
}
