// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ReisekostenNative.iOS
{
	public partial class BelegeTableViewController : UITableViewController
	{
		public BelegeTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
