// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ReisekostenNative.iOS
{
    public partial class BelegOeffnenSegue : UIStoryboardSegue
	{
        public BelegOeffnenSegue (IntPtr handle) : base (handle)
		{
		}

        public override void Perform()
        {

            var src = SourceViewController as BelegeTableViewController;
            var dest = SourceViewController as BelegNeuTableViewController; 
            if (src != null && dest != null) {
                    // TODO restcall ...

            }
        }
	}
}
