// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ReisekostenNative.iOS
{
	public partial class LoginViewController : UIViewController
	{
		public LoginViewController (IntPtr handle) : base (handle)
		{
		}

        public string getUser() {
            return benutzer.Text;
        }

        public bool isDataValid() {
            return benutzer.Text != null && benutzer.Text.Length > 0;
        }
	}
}
