// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ReisekostenNative.iOS
{
    public partial class LoginSegue : UIStoryboardSegue
    {
        public LoginSegue(IntPtr handle) : base(handle)
        {
        }

        public override void Perform()
        {

            var src = SourceViewController as LoginViewController;
            var dest = SourceViewController as BelegeTableViewController;
            if (src != null && dest != null)
            {
                dest.setUser(src.getUser());
            }
            src.ShowViewController(dest, null);
        }
    }
}
